# Generated by Django 4.0.1 on 2022-01-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apis',
            old_name='name',
            new_name='API',
        ),
        migrations.RenameField(
            model_name='apis',
            old_name='auth',
            new_name='Auth',
        ),
        migrations.RenameField(
            model_name='apis',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='apis',
            old_name='cors',
            new_name='Cors',
        ),
        migrations.RenameField(
            model_name='apis',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='apis',
            old_name='https',
            new_name='HTTPS',
        ),
        migrations.RenameField(
            model_name='apis',
            old_name='link',
            new_name='Link',
        ),
    ]
