# Generated by Django 4.0.1 on 2022-01-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_name_apis_api_rename_auth_apis_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='Auth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
