# Generated by Django 4.0.1 on 2022-01-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_apis_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='Cors',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='apis',
            name='Link',
            field=models.CharField(max_length=100),
        ),
    ]
