# Generated by Django 4.0.1 on 2022-01-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_apis_cors_alter_apis_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='Link',
            field=models.CharField(max_length=150),
        ),
    ]
